// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdcAU57XXVQjA7USRXQVN_FGPqctwmT2w',
    appId: '1:716936334541:android:814a46038e593da7c52d84',
    messagingSenderId: '716936334541',
    projectId: 'gaanap-live-10003',
    databaseURL: 'https://gaanap-live-10003.firebaseio.com',
    storageBucket: 'gaanap-live-10003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ0F3gSbYm17OoKpkDazFPqP5Wxo4MrDw',
    appId: '1:716936334541:ios:317fa1ded3615aaac52d84',
    messagingSenderId: '716936334541',
    projectId: 'gaanap-live-10003',
    databaseURL: 'https://gaanap-live-10003.firebaseio.com',
    storageBucket: 'gaanap-live-10003.appspot.com',
    androidClientId: '716936334541-684gs5n3d615d63cd3hfjq348m6nrjpg.apps.googleusercontent.com',
    iosClientId: '716936334541-gsphal6iu46hpbtmjuqk718060p2tod5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gaanapAdminNew',
  );
}
